name: cheapBuy
language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - pytest test/test.py
  - pytest test/test2.py
  - pytest test/test3.py
  - pytest test/test5.py
