name: Format
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - run: npm install 
      - run: npm ci
      - run: npm run format
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply formatting changes
          branch: ${{ github.head_ref }}
# name: black-action
# on: [push, pull_request]
# jobs:
#   linter_name:
#     name: runner / black
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Check files using the black formatter
#         uses: rickstaa/action-black@v1
#         id: action_black
#         with:
#           black_args: "."
#       - name: Create Pull Request
#         if: steps.action_black.outputs.is_formatted == 'true'
#         uses: peter-evans/create-pull-request@v3
#         with:
#           token: ${{ secrets.GITHUB_TOKEN }}
#           title: "Format Python code with psf/black push"
#           commit-message: ":art: Format Python code with psf/black"
#           body: |
#             There appear to be some python formatting errors in ${{ github.sha }}. This pull request
#             uses the [psf/black](https://github.com/psf/black) formatter to fix these issues.
#           base: ${{ github.head_ref }} # Creates pull request onto pull request or commit branch
#           branch: actions/black

# name: Format
# on: pull_request:
#       branches: [main]
# jobs:
#   linter_name:
#     name: runner / black formatter
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#         with:
#           ref: ${{ github.head_ref }}
#       - uses: rickstaa/action-black@v1
#         with:
#           black_args: ". --check"
#         with:
#           commit_message: Apply formatting changes
#           branch: ${{ github.head_ref }}